//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NastinCOFE.DBS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gender
    {
        public string IDGender { get; set; }
        public string NameOfGender { get; set; }
    }
}
